[bucket]
bucket_name = nu-cs-msa-s3-photoapp
region_name = us-east-2

[webserver]
endpoint = https://nu-cs-msa-s3-photoapp.s3.us-east-2.amazonaws.com

[ui]
banner_start = **Starting**
banner_done = **Done**
# Trailing space after > is enforced in code (ConfigParser strips line ends).
prompt_download = Enter image to download without extension>
