import PDFDocument from 'pdfkit';
import { createWriteStream, existsSync, mkdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const FIXTURES_DIR = __dirname;

export const RUN_ID = randomUUID();

async function generateTestPdf(): Promise<string> {
  const path = join(FIXTURES_DIR, 'test-fixture.pdf');
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    const stream = createWriteStream(path);
    doc.pipe(stream);
    doc.fontSize(20).text('E2E Test Fixture — DO NOT KEEP', 50, 100);
    doc.fontSize(12).text(`Run ID: ${RUN_ID}`, 50, 150);
    doc.fontSize(10).text('Generated by playwright global setup. Safe to delete.', 50, 180);
    doc.end();
    stream.on('finish', () => resolve(path));
    stream.on('error', reject);
  });
}

async function generateOversizedBlob(): Promise<string> {
  const path = join(FIXTURES_DIR, 'oversized.bin');
  if (existsSync(path) && statSync(path).size > 50 * 1024 * 1024) {
    return path;
  }
  const { writeFile } = await import('node:fs/promises');
  const buf = Buffer.alloc(51 * 1024 * 1024, 0);
  await writeFile(path, buf);
  return path;
}

export default async function globalSetup() {
  if (!existsSync(FIXTURES_DIR)) mkdirSync(FIXTURES_DIR, { recursive: true });
  const pdfPath = await generateTestPdf();
  const blobPath = await generateOversizedBlob();
  console.log(`[e2e/fixtures/setup] PDF generated at ${pdfPath}`);
  console.log(`[e2e/fixtures/setup] oversized blob generated at ${blobPath}`);
  console.log(`[e2e/fixtures/setup] RUN_ID = ${RUN_ID}`);
}
